# Generated by Django 2.0.4 on 2018-06-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180520_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_desc',
            field=models.CharField(blank=True, max_length=254, verbose_name='Подпись под обложкой'),
        ),
    ]
